apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydep
  name: mydep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
  selector:
    app: mydep
  type: NodePort
